---
extends: egg
parserOptions:
  sourceType: module
rules:
  comma-dangle: [2, 'always-multiline']
  babel/generator-star-spacing: off
  generator-star-spacing: off
  space-before-function-paren: [2, 'always']
  newline-per-chained-call: 2
  array-bracket-spacing: 2
  no-else-return: 2
  valid-jsdoc: 2
  eol-last: 2
  no-debugger: 0
  no-console: 0
  no-alert: 0
